-- BigQuery view i4g_ml.actor_features
-- Defines the contract for actor-level features generated by I4G core and consumed by ML.

CREATE OR REPLACE VIEW `i4g_ml.actor_features` AS
SELECT
    actor_id,
    -- Basic features
    active_campaigns_count,
    first_seen_timestamp,
    last_seen_timestamp,
    -- Requested specific features
    co_actor_count AS co_membership_degree,
    cross_campaign_domain_count,
    leak_count,
    blocklist_hit_count,
    total_damage_usd_estimate AS damage_confirmed_total
FROM
    `i4g_core.threat_actors` -- Note: Actual source tables would be joined here; this is a schema contract definition.
    -- The core ingestion populates these fields or they are aggregated via a materialized view on the core side.
